name: ci
on: [pull_request, push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - run: go vet ./...
      - run: go test ./...
      - uses: golangci/golangci-lint-action@v7
        with:
          version: "v2"
